# Based on: https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p logs/slurm &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem="{resources.mem_gb}G"
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time}
    --output=logs/slurm/{rule}-{wildcards}-%j.log
    --verbose
    --parsable
default-resources:
  - account=2023-bjp-rmre-seq
  - partition=compute
  - time=120
  - mem_gb=8
restart-times: 3
local-cores: 6
latency-wait: 1800
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
reason: True
conda-frontend: conda
cluster-status: scripts/status.py
cluster-cancel: scancel
max-status-checks-per-second: 5

# rerun-trigger: mtime
